sync_all_imap_connections:
  class: SyncAllImapConnectionsJob
  schedule: every 5 minutes
  queue: webhooks

reconcile_all_drafts:
  class: ReconcileAllDraftsJob
  schedule: every 5 minutes
  queue: mailers
